import os
import sys
from datetime import datetime

# Add current directory to path to import local modules
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from fetch_papers import fetch_daily_papers
from download_papers import download_all_papers
from summarize_papers import extract_text_from_pdf, summarize_paper

def generate_markdown_report(summaries, date_str):
    """Generates a comprehensive Markdown report from the paper summaries."""
    report = f"# Daily Hugging Face Paper Digest - {date_str}\n\n"
    report += f"This report was automatically generated by the Manus AI tool on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}.\n\n"
    report += "## Summary of Papers\n\n"
    
    for i, summary_data in enumerate(summaries, 1):
        paper = summary_data['paper']
        summary = summary_data['summary']
        
        report += f"--- \n\n"
        report += f"## {i}. {paper['title']}\n\n"
        report += f"**Authors:** {', '.join(paper['authors'])}\n\n"
        report += f"**Published:** {paper['published_at'][:10]}\n\n"
        
        # Format the summary content
        # The summary is already in the requested format, so we just need to clean it up
        report += summary.strip() + "\n\n"
        
        # Add a table for quick links
        links = [
            ("Hugging Face", paper.get('hf_url', 'N/A')),
            ("ArXiv Abstract", paper.get('arxiv_url', 'N/A')),
            ("PDF Download", paper.get('pdf_url', 'N/A'))
        ]
        
        # Attempt to extract GitHub link from the summary text
        github_link = "N/A"
        for line in summary.split('\n'):
            if 'Github:' in line:
                github_link = line.split('Github:')[1].strip()
                break
        if github_link != "N/A":
            links.append(("GitHub", github_link))

        report += "### Related Links\n\n"
        report += "| Platform | Link |\n"
        report += "| :--- | :--- |\n"
        for platform, link in links:
            # Clean up the link if it's part of the summary text and includes the label
            if platform == "GitHub" and "Github:" in link:
                link = link.replace("Github:", "").strip()
            
            # Ensure the link is a proper URL before creating a Markdown link
            if link.startswith('http'):
                report += f"| {platform} | [{link}]({link}) |\n"
            else:
                report += f"| {platform} | {link} |\n"
        report += "\n"
        
    return report

def run_daily_digest(date_str):
    """Main function to run the daily paper digest process."""
    print(f"--- Starting Daily Paper Digest for {date_str} ---")
    
    # 1. Get the paper list
    print("Phase 1: Fetching paper list...")
    papers = fetch_daily_papers(date_str)
    if not papers:
        print("No papers found or error in fetching. Exiting.")
        return
    print(f"Found {len(papers)} papers.")
    
    # 2. Download all the papers
    print("Phase 2: Downloading PDFs...")
    download_all_papers(papers, download_dir="papers")
    
    # 3 & 4. Read and Summarize each paper
    print("Phase 3 & 4: Reading and Summarizing papers...")
    summaries = []
    for i, paper in enumerate(papers):
        print(f"Processing paper {i+1}/{len(papers)}: {paper['title']}")
        
        # Check if the paper was successfully downloaded
        if 'local_path' not in paper or not os.path.exists(paper['local_path']):
            print(f"Skipping paper {paper['id']}: PDF not found.")
            continue
            
        text = extract_text_from_pdf(paper['local_path'])
        summary_text = summarize_paper(paper, text)
        
        summaries.append({
            'paper': paper,
            'summary': summary_text
        })
        
    # 5. Make a comprehension Markdown Report
    print("Phase 5: Generating Markdown Report...")
    markdown_report = generate_markdown_report(summaries, date_str)
    
    report_filename = f"daily_digest_{date_str}.md"
    with open(report_filename, 'w') as f:
        f.write(markdown_report)
        
    print(f"--- Digest Complete. Report saved to {report_filename} ---")
    return report_filename

if __name__ == "__main__":
    # Use the date from the user's image for a complete test
    target_date = "2026-01-02"
    run_daily_digest(target_date)
